### ISSUE TITLE
SeDumi not installed successfully on Matlab_R2017b

### ISSUE THREAD

**Issue by izzy2512** [sqlp/sedumi#35]
I have downloaded Sedumi from https://github.com/SQLP/SeDuMi and installed it, however it is still not working. When I tried to re-build it, I got this message saying:

'' Warning: Xcode is installed, but its license has not been accepted. Run Xcode
and accept its license agreement.

At least one compilation failure occurred.
---------------------------------------------------------------------------
SeDuMi was not successfully installed.
Please attempt to correct the errors and try again.''

I don't know what the Xcode is.

Also ''its license has not been accepted" what does that mean? 
Could you help me?

greatly appreciate your help.

**Comment by siko1056** [comment]
From your error message I conclude, that you are running Matlab R2017b on macOS, right?

A short Q&A with Google delivers this page: https://developer.apple.com/xcode/

The answer is fully contained in the error message:  Start a program on your macOS called "Xcode", accept blindly whatever they demand from you to accept, and you'll become a happy user of three softwares:  [Xcode](https://developer.apple.com/xcode/), MATLAB's [mex compiler](https://www.mathworks.com/support/compilers.html) which uses Xcode as backend, and SeDuMi, which makes use of the mex compiler to compile the C sourcecode in a MATLAB compatible way.

If you don't face any further issues, please don't forget to close this issue.

**Comment by izzy2512** [comment]
Dear Siko1056, I've downloaded Xcode as you suggested and tried to install sedumi, this is what happened (beware of a very long long message lol ):


install_sedumi -rebuild

---------------------------------------------------------------------------
SeDuMi installation script
   Directory: /Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master
   Matlab 9.3.0.713579 (R2017b) on MACI64
---------------------------------------------------------------------------
Attempting to recompile the SeDuMi binaries:
Template: mex -O -largeArrayDims <sources> -lmwblas
   bwblkslv.mexmaci64: bwblkslv.c sdmauxFill.c sdmauxRdot.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

   choltmpsiz.mexmaci64: choltmpsiz.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   cholsplit.mexmaci64: cholsplit.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   dpr1fact.mexmaci64: dpr1fact.c auxfwdpr1.c sdmauxCone.c  sdmauxCmp.c sdmauxFill.c sdmauxScalarmul.c sdmauxRdot.c blkaux.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

   symfctmex.mexmaci64: symfctmex.c symfct.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/symfctmex.c:192:3: warning: implicit declaration of function 'sfinit_' is invalid in C99 [-Wimplicit-function-declaration]
  sfinit_(&m, Xjc+m,  xadj,adjncy, perm, invp, colcnt,
  ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/symfctmex.c:209:3: warning: implicit declaration of function 'symfct_' is invalid in C99 [-Wimplicit-function-declaration]
  symfct_(&m, Xjc+m,xadj,adjncy, perm,invp,colcnt,
  ^
2 warnings generated.

MEX completed successfully.
   ordmmdmex.mexmaci64: ordmmdmex.c ordmmd.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/ordmmdmex.c:122:3: warning: implicit declaration of function 'ordmmd_' is invalid in C99 [-Wimplicit-function-declaration]
  ordmmd_(&m,xadj,adjncy, invp,perm, &iwsiz,iwork, &nofsub, &flag);
  ^
1 warning generated.

MEX completed successfully.
   quadadd.mexmaci64: quadadd.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   sqrtinv.mexmaci64: sqrtinv.c sdmauxCone.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   givensrot.mexmaci64: givensrot.c auxgivens.c sdmauxCone.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   urotorder.mexmaci64: urotorder.c auxgivens.c sdmauxCone.c sdmauxTriu.c sdmauxRdot.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

   psdframeit.mexmaci64: psdframeit.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   psdinvjmul.mexmaci64: psdinvjmul.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c blkaux.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   bwdpr1.mexmaci64: bwdpr1.c sdmauxCone.c sdmauxRdot.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

   fwdpr1.mexmaci64: fwdpr1.c auxfwdpr1.c sdmauxCone.c sdmauxScalarmul.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   fwblkslv.mexmaci64: fwblkslv.c sdmauxScalarmul.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   qblkmul.mexmaci64: qblkmul.c sdmauxScalarmul.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   blkchol.mexmaci64: blkchol.c blkchol2.c sdmauxFill.c sdmauxScalarmul.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blkchol2.c:56:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&n,&alpha,x,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:197:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blkchol2.c:69:19: warning: implicit declaration of function 'idamax__' is invalid in C99 [-Wimplicit-function-declaration]
    return fabs(x[FORT(idamax)(&nn,(double*)x,&one)]);
                  ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:199:1: note: expanded from here
idamax__
^
2 warnings generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   vecsym.mexmaci64: vecsym.c sdmauxCone.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   qrK.mexmaci64: qrK.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   finsymbden.mexmaci64: finsymbden.c sdmauxCmp.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   symbfwblk.mexmaci64: symbfwblk.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   whichcpx.mexmaci64: whichcpx.c sdmauxCone.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   ddot.mexmaci64: ddot.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   makereal.mexmaci64: makereal.c sdmauxCone.c sdmauxCmp.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   partitA.mexmaci64: partitA.c sdmauxCmp.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   getada1.mexmaci64: getada1.c sdmauxFill.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   getada2.mexmaci64: getada2.c sdmauxCone.c sdmauxRdot.c sdmauxFill.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

   getada3.mexmaci64: getada3.c spscale.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c sdmauxCmp.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

   adendotd.mexmaci64: adendotd.c sdmauxCone.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   adenscale.mexmaci64: adenscale.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   extractA.mexmaci64: extractA.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   vectril.mexmaci64: vectril.c sdmauxCone.c sdmauxCmp.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   qreshape.mexmaci64: qreshape.c sdmauxCone.c sdmauxCmp.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   sortnnz.mexmaci64: sortnnz.c sdmauxCmp.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   iswnbr.mexmaci64: iswnbr.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   incorder.mexmaci64: incorder.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   findblks.mexmaci64: findblks.c sdmauxCone.c sdmauxCmp.c
Building with 'Xcode with Clang'.
MEX completed successfully.
   invcholfac.mexmaci64: invcholfac.c triuaux.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c blkaux.c
Building with 'Xcode with Clang'.
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
ddot__
^
1 warning generated.

/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:44:5: warning: implicit declaration of function 'dcopy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dcopy)(&nn,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:570:1: note: expanded from here
dcopy__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:45:5: warning: implicit declaration of function 'dscal__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(dscal)(&nn,&alpha,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:572:1: note: expanded from here
dscal__
^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/sdmauxScalarmul.c:55:5: warning: implicit declaration of function 'daxpy__' is invalid in C99 [-Wimplicit-function-declaration]
    FORT(daxpy)(&nn,&alpha,(double*)x,&one,r,&one);
    ^
/Users/isaiasaraya/Documents/MATLAB/UROP/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017b.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:574:1: note: expanded from here
daxpy__
^
3 warnings generated.

At least one compilation failure occurred.
---------------------------------------------------------------------------
SeDuMi was not successfully installed.
Please attempt to correct the errors and try again.
---------------------------------------------------------------------------



Thanks for your help

**Comment by siko1056** [comment]
This issue was solved recently: https://github.com/sqlp/sedumi/issues/26#issuecomment-349094575

**Comment by izzy2512** [comment]
I've done as you suggested, I found the file you said ''sedumi-master/sdmauxRdot.c'' and I replaced ''return FORT(ddot)(&nn)'' with ''return ddot_(&nn...)'' in lines 47 and 57 but I'm still getting the same error message as before.

Any other solutions? Also when I try sedumi(1,1,1)  get this message =:
SeDuMi 1.32 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta = 0.500
Undefined function or variable 'qrK'.

Error in sdinit (line 86)
vfrm.s = qrK(d.u,K);

Error in sedumi (line 401)
[d, v,vfrm, y,y0, R] = sdinit(A,b,c,dense,K,pars);

**Comment by siko1056** [comment]
Please revert that change, and do exactly what is written in the comment, where the link of my previous post points to:

> -#define FORT(x) FORTRAN_WRAPPER(x)
> +#define FORT(x) x
>
> at line at line 45 in blksdp.h

That was the solution of #26 .
